---
title: "Analysis"
author: "Holly W, Charlie C, Manal P"
date: "2025-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import data

and make columns uniform

```{r}
library(readxl)
a = read_excel("A.xlsx")
b = read_excel("B.xlsx")
p = read_excel("P.xlsx")
se = read_excel("SouthEast.xlsx")
d = read.csv("data_entry.csv")
colnames(se) = c("Age","PH","MH","Smoker","Belief","SES5","Gender","Region","ID")
se$ID = NULL

colnames(d) = c("Name","Age","Gender","Belief","PH","MH")
d$Name = NULL
d$Smoker = d$Region = d$SES5 = NA

```

## Merge

```{r}
datasets <- list(a,b,p)
abp = Reduce(function(x,y) rbind(x,y,all=TRUE), datasets)
abp_se = rbind(abp,se)
alldata = rbind(abp_se,d)
```

## Change belief to binary 

```{r}
library(dplyr)
binarycols = c("Belief")
alldata <-  alldata %>%
  mutate(across(
    all_of(binarycols),
    ~ case_when(
      . == "Y" ~ 1,
      . == "N" ~ 0,
      . == "U" ~ NA_real_,
      TRUE ~ NA_real_     
    )
  ))
```
# Coding variables

```{r}
# Coding Smoker variable
alldata$Smoker[alldata$Smoker %in% c("Current","TRUE","Y")] = 1
alldata$Smoker[alldata$Smoker == "N"] = 0

# Coding SES5 variable
alldata$SES5 <- ifelse(alldata$SES5 == "L1", 1,
                         ifelse(alldata$SES5 == "L2", 2,
                                ifelse(alldata$SES5 == "L3", 3,
                                       ifelse(alldata$SES5 == "L4", 4,
                                              ifelse(alldata$SES5 == "L5", 5,alldata$SES5)))))
alldata$SES5[alldata$SES5== "TRUE"] = NA

# Coding PH variable
alldata$PH[alldata$PH %in% c("N","No","NO")] = 0
alldata$PH[alldata$PH %in% c("TRUE","Y","Yes","YES")] = 1

# Coding MH variable
alldata$MH[alldata$MH %in% c("N","No","NO")] = 0
alldata$MH[alldata$MH %in% c("TRUE","Y","Yes","YES")] = 1

# Coding Gender variable
alldata$Gender[alldata$Gender %in% c("F","Female")] = "F"
alldata$Gender[alldata$Gender %in% c("M","Male")] = "M"
alldata$Gender[alldata$Gender %in% c("GD")] = "GD"
alldata$Gender[!(alldata$Gender %in% c("F","Female","GD","M","Male"))] = NA

# Make variables factors
alldata$PH <- factor(alldata$PH)
alldata$Smoker <- factor(alldata$Smoker)
alldata$SES5 <- factor(alldata$SES5)
```

## Model 

```{r}
model <- glm(
  Belief ~ MH + PH,
  data = alldata,
  family = binomial
)
summary(model)
```